#!/usr/bin/env python3
"""Coordinate work in the shared space through the swarm core (generated by stormo).

Locks, who changed a file, and change notes, for terminal use and scripts. It calls the core's
MCP tools (fs_*) as this agent: SWARM_CORE_URL and SWARM_CORE_KEY come from the environment.

  workdir.py lock PATH [--kind hard|soft|temp] [--reason TEXT] [--minutes N]
  workdir.py unlock PATH
  workdir.py renew PATH [--minutes N]
  workdir.py locks [PATH]
  workdir.py info PATH
  workdir.py ls [DIR]
  workdir.py note PATH [--action created|modified|deleted]

PATH may be relative to the current directory; it must end up under /shared/group or
/shared/zzunitzz. Exit status 1 with the core's reason when it refuses (for example: locked).
"""
import argparse
import json
import os
import sys
import urllib.error
import urllib.request


def call(tool, args):
    url = os.environ.get("SWARM_CORE_URL", "http://host.docker.internal:18600").rstrip("/") + "/mcp"
    key = os.environ.get("SWARM_CORE_KEY", "")
    if not key:
        sys.exit("workdir.py: SWARM_CORE_KEY is not set (this helper works in local runs on the core)")
    body = json.dumps({"jsonrpc": "2.0", "id": 1, "method": "tools/call",
                       "params": {"name": tool, "arguments": args}}).encode()
    req = urllib.request.Request(url, data=body, method="POST", headers={
        "Content-Type": "application/json",
        "Accept": "application/json, text/event-stream",
        "Authorization": "Bearer " + key,
    })
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            out = json.load(r)
    except urllib.error.HTTPError as e:
        sys.exit(f"workdir.py: the core answered HTTP {e.code}")
    except urllib.error.URLError as e:
        sys.exit(f"workdir.py: the core is not reachable at {url} ({e.reason})")
    if "error" in out:
        sys.exit("workdir.py: " + out["error"].get("message", "error"))
    res = out["result"]
    text = res["content"][0]["text"] if res.get("content") else ""
    if res.get("isError"):
        print(text, file=sys.stderr)
        sys.exit(1)
    return res.get("structuredContent") or (json.loads(text) if text else {})


def absolute(p):
    return os.path.normpath(os.path.join(os.getcwd(), p)) if p else p


def main():
    ap = argparse.ArgumentParser(description="Shared-space locks and history through the swarm core.")
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("lock")
    p.add_argument("path")
    p.add_argument("--kind", default="hard", choices=["hard", "soft", "temp"])
    p.add_argument("--reason", default="")
    p.add_argument("--minutes", type=int, default=0)
    p = sub.add_parser("unlock")
    p.add_argument("path")
    p = sub.add_parser("renew")
    p.add_argument("path")
    p.add_argument("--minutes", type=int, default=0)
    p = sub.add_parser("locks")
    p.add_argument("path", nargs="?", default="")
    p = sub.add_parser("info")
    p.add_argument("path")
    p = sub.add_parser("ls")
    p.add_argument("path", nargs="?", default=".")
    p = sub.add_parser("note")
    p.add_argument("path")
    p.add_argument("--action", default="modified", choices=["created", "modified", "deleted"])
    a = ap.parse_args()

    path = absolute(a.path) if getattr(a, "path", "") else ""
    if a.cmd == "lock":
        args = {"path": path, "kind": a.kind, "reason": a.reason}
        if a.minutes:
            args["minutes"] = a.minutes
        out = call("fs_lock", args)
        lock = out["lock"]
        print(f"locked {lock['path']} ({lock['kind']}) until {lock['expires']}")
        for w in out.get("warnings") or []:
            print("note: " + w)
    elif a.cmd == "unlock":
        call("fs_unlock", {"path": path})
        print(f"released {path}")
    elif a.cmd == "renew":
        args = {"path": path}
        if a.minutes:
            args["minutes"] = a.minutes
        lock = call("fs_renew", args)
        print(f"renewed {lock['path']} until {lock['expires']}")
    elif a.cmd == "locks":
        out = call("fs_locks", {"path": path} if path else {})
        for l in out.get("locks") or []:
            print(f"{l['path']}\t{l['owner']}\t{l['kind']}\tuntil {l['expires']}\t{l.get('reason', '')}")
    elif a.cmd == "info":
        print(json.dumps(call("fs_info", {"path": path}), indent=1))
    elif a.cmd == "ls":
        out = call("fs_ls", {"path": path})
        for e in out.get("entries") or []:
            name = e["name"] + ("/" if e.get("dir") else "")
            print(f"{name}\t{e.get('lastWriter', '') or '-'}\t{e.get('locked', '')}")
    elif a.cmd == "note":
        call("fs_note", {"path": path, "action": a.action})
        print(f"noted: you {a.action} {path}")


if __name__ == "__main__":
    main()
