package local

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/camfinc/stormo/pkg/aws"
	"github.com/camfinc/stormo/pkg/build"
	"github.com/camfinc/stormo/pkg/deploy"
	"github.com/camfinc/stormo/pkg/engines"
	"github.com/camfinc/stormo/pkg/instance"
	"github.com/camfinc/stormo/pkg/manifest"
	"github.com/camfinc/stormo/pkg/place"
	"github.com/camfinc/stormo/pkg/secrets"
	"github.com/camfinc/stormo/pkg/shared"
	"go.yaml.in/yaml/v3"
)

func compose(root string, a *manifest.Agent, quiet bool, args ...string) (string, error) {
	cc, err := ComposeCommand()
	if err != nil {
		return "", err
	}
	argv := append(append(cc, "-p", ProjectName(a), "-f", ComposePath(root, a)), args...)
	cmd := exec.Command(argv[0], argv[1:]...)
	var out bytes.Buffer
	if quiet {
		cmd.Stdout = &out
	} else {
		cmd.Stdout = os.Stdout
	}
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return "", fmt.Errorf("%s exited: %w", strings.Join(argv, " "), err)
	}
	return out.String(), nil
}

// UpOptions for Up.
type UpOptions struct {
	// Vouch that ECS is stopped when it cannot be checked (no AWS access).
	AllowProdToken bool
	// ECS state already established by the caller (handoff), skipping the check.
	Other          place.SideState
	KeepHome       bool
	NapInterval    int
	RebuildSidecar bool
	Log            func(string)
}

// Up builds, renders and (re)starts one agent locally. By default the agent's home is discarded
// and rebuilt by rehydrate from the latest local nap, exactly like an ECS redeploy; KeepHome skips
// that for the fastest possible restart.
func Up(inst *instance.Instance, id string, o UpOptions) (int, []manifest.Off, error) {
	if o.Log == nil {
		o.Log = func(string) {}
	}
	root := inst.Root
	a, err := manifest.Load(root, id, inst.Names.Secret)
	if err != nil {
		return 0, nil, err
	}
	eng, err := engines.Get(a.Engine.Kind, inst)
	if err != nil {
		return 0, nil, err
	}
	file, err := secrets.Load(secrets.Path(root))
	if err != nil {
		return 0, nil, err
	}
	resolved := secrets.Resolve(file, a, manifest.Local)
	if len(resolved.Missing) > 0 {
		return 0, nil, fmt.Errorf("%s: missing secrets %s in %s (stormo secrets init / check)", id, strings.Join(resolved.Missing, ", "), secrets.Path(root))
	}
	// One place at a time: on the production Slack app, start only if ECS is not running it (a
	// separate dev app under local.agents.<id> may run alongside).
	sharedTokens := len(secrets.ProdTokenClashes(file, a)) > 0
	other := o.Other
	if other == "" {
		other = place.Unknown
		if sharedTokens {
			other = place.RemoteSide(inst, id, aws.Exec, deploy.DefaultTarget(inst))
		}
	}
	if g := place.GuardStart(id, place.Local, other, sharedTokens, o.AllowProdToken); !g.OK {
		return 0, nil, fmt.Errorf("%s", g.Reason)
	}

	// Optional secrets without a value leave out what they gate (skills, actions, channels).
	r, err := build.Agent(inst, id, build.Options{Target: manifest.Local, Present: resolved.Values.Keys()})
	if err != nil {
		return 0, nil, err
	}
	envFile, _, err := secrets.WriteLocalEnv(root, a)
	if err != nil {
		return 0, nil, err
	}
	storeDir := filepath.Join(root, ".swarm", "store")
	sharedDir := shared.LocalDir(root)
	moved, conflicts, err := shared.MigrateLocal(root)
	if err != nil {
		return 0, nil, fmt.Errorf("moving .swarm/shared to workdir/: %w", err)
	}
	{
		for _, l := range moved {
			o.Log(fmt.Sprintf("shared space: moved .swarm/shared/%s to workdir/%s", l, l))
		}
		for _, l := range conflicts {
			o.Log(fmt.Sprintf("WARNING: .swarm/shared/%s and workdir/%s both exist; agents now mount workdir/%s, merge the old one by hand", l, l, l))
		}
	}
	if err := os.MkdirAll(storeDir, 0o755); err != nil {
		return 0, nil, err
	}
	for _, l := range shared.Layers(a) {
		if err := os.MkdirAll(filepath.Join(sharedDir, l.Layer), 0o755); err != nil {
			return 0, nil, err
		}
	}
	image, err := EnsureSidecar(o.RebuildSidecar, o.Log)
	if err != nil {
		return 0, nil, err
	}
	port, err := Port(root, id)
	if err != nil {
		return 0, nil, err
	}
	interval := o.NapInterval
	if interval == 0 {
		interval = 120
	}
	spec := Render(r.Agent, eng, Paths{Root: root, BaselineDir: r.Out, EnvFile: envFile, StoreDir: storeDir, SharedDir: sharedDir}, port, interval, image)
	var b bytes.Buffer
	enc := yaml.NewEncoder(&b)
	enc.SetIndent(2)
	if err := enc.Encode(spec); err != nil {
		return 0, nil, err
	}
	if err := secrets.WritePrivate(ComposePath(root, a), append([]byte("# GENERATED by `stormo start`. Do not edit.\n"), b.Bytes()...)); err != nil {
		return 0, nil, err
	}
	// Stop (agent first, then nap's final snapshot), drop the home volume, start fresh.
	down := []string{"down", "--timeout", "100"}
	if !o.KeepHome {
		down = append(down, "--volumes")
	}
	if _, err := compose(root, a, false, down...); err != nil {
		return 0, nil, err
	}
	if _, err := compose(root, a, false, "up", "-d", "--force-recreate"); err != nil {
		return 0, nil, err
	}
	return port, r.Off, nil
}

func load(inst *instance.Instance, id string) (*manifest.Agent, error) {
	return manifest.Load(inst.Root, id, inst.Names.Secret)
}

// Down stops an agent (agent first, then nap's final snapshot) and drops its home volume.
func Down(inst *instance.Instance, id string) error {
	a, err := load(inst, id)
	if err != nil {
		return err
	}
	if _, err := os.Stat(ComposePath(inst.Root, a)); os.IsNotExist(err) {
		return nil // never started here
	}
	_, err = compose(inst.Root, a, false, "down", "--timeout", "100", "--volumes")
	return err
}

func Logs(inst *instance.Instance, id string, follow bool) error {
	a, err := load(inst, id)
	if err != nil {
		return err
	}
	args := []string{"logs", "--tail", "200"}
	if follow {
		args = append(args, "-f")
	}
	_, err = compose(inst.Root, a, false, args...)
	return err
}

// NapNow takes a nap right now (instead of waiting for the interval), e.g. before a dream.
func NapNow(inst *instance.Instance, id string) error {
	a, err := load(inst, id)
	if err != nil {
		return err
	}
	_, err = compose(inst.Root, a, false, "exec", "-T", "nap", "stormo", "nap")
	return err
}

// Chat sends one message to the agent's local API server (OpenAI-compatible chat completions).
func Chat(inst *instance.Instance, id, message, session string) (string, error) {
	a, err := load(inst, id)
	if err != nil {
		return "", err
	}
	file, err := secrets.Load(secrets.Path(inst.Root))
	if err != nil {
		return "", err
	}
	key, _ := secrets.Resolve(file, a, manifest.Local).Values.Get("API_SERVER_KEY")
	if key == "" {
		return "", fmt.Errorf("%s: API_SERVER_KEY missing in %s", id, secrets.Path(inst.Root))
	}
	port, err := Port(inst.Root, id)
	if err != nil {
		return "", err
	}
	body, _ := json.Marshal(map[string]any{"model": "hermes-agent", "messages": []map[string]string{{"role": "user", "content": message}}})
	req, _ := http.NewRequest("POST", fmt.Sprintf("http://127.0.0.1:%d/v1/chat/completions", port), bytes.NewReader(body))
	req.Header.Set("Authorization", "Bearer "+key)
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("X-Hermes-Session-Id", session)
	res, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", err
	}
	defer res.Body.Close()
	raw, _ := io.ReadAll(res.Body)
	if res.StatusCode >= 300 {
		return "", fmt.Errorf("%s: HTTP %d %s", id, res.StatusCode, raw)
	}
	var out struct {
		Choices []struct {
			Message struct {
				Content string `json:"content"`
			} `json:"message"`
		} `json:"choices"`
	}
	if err := json.Unmarshal(raw, &out); err != nil || len(out.Choices) == 0 {
		return "", err
	}
	return out.Choices[0].Message.Content, nil
}
