// Package scaffold creates a new instance directory: `stormo new instance` (docs/instances.md).
package scaffold

import (
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/camfinc/stormo/pkg/instance"
)

// Templates a new instance can start from.
const (
	// Empty is a stormo.yaml and the group unit: the start of a real organisation's instance.
	Empty = "empty"
	// Example is the example instance (Acme: two units, three agents) under the new name.
	Example = "example"
)

// Options for NewInstance. Name is required; Org defaults to Name, Slug to one derived from Name.
type Options struct {
	Name, Org, Slug string
	Template        string
	// Git runs `git init` in the new directory when git is installed (nothing is committed).
	Git bool
}

// Result is what NewInstance made.
type Result struct {
	Root     string `json:"root"`
	Name     string `json:"name"`
	Org      string `json:"org"`
	Slug     string `json:"slug"`
	Template string `json:"template"`
	Git      bool   `json:"git"`
}

var nonSlug = regexp.MustCompile(`[^a-z0-9]+`)

// SlugFrom derives a slug from a display name: "Acme Swarm" → "acme-swarm"; "" when none fits.
func SlugFrom(name string) string {
	s := strings.Trim(nonSlug.ReplaceAllString(strings.ToLower(name), "-"), "-")
	s = strings.TrimLeft(s, "0123456789-")
	if !instance.ValidSlug(s) {
		return ""
	}
	return s
}

// The engine's generated and local-only files, never in an instance's git history.
const gitignore = `# Generated by stormo, and local only. Never commit.
dist/
.swarm/
secrets.local.yaml
*.secrets.yaml
.env
.env.*
.DS_Store
`

// NewInstance creates dir (absent or empty) as an instance from the template. example is the
// example instance's files (stormo.Example()). On failure nothing it created is left behind.
func NewInstance(dir string, o Options, example fs.FS) (Result, error) {
	o.Name = strings.TrimSpace(o.Name)
	if o.Name == "" {
		return Result{}, errors.New("a name is required (--name)")
	}
	if o.Org = strings.TrimSpace(o.Org); o.Org == "" {
		o.Org = o.Name
	}
	if o.Slug == "" {
		o.Slug = SlugFrom(o.Name)
	}
	if !instance.ValidSlug(o.Slug) {
		return Result{}, fmt.Errorf("slug %q: lowercase letters, digits and hyphens, starting with a letter (--slug)", o.Slug)
	}
	if o.Template == "" {
		o.Template = Empty
	}
	if o.Template != Empty && o.Template != Example {
		return Result{}, fmt.Errorf("template %q: empty or example", o.Template)
	}
	root, err := filepath.Abs(dir)
	if err != nil {
		return Result{}, err
	}
	created, err := prepare(root)
	if err != nil {
		return Result{}, err
	}
	fail := func(err error) (Result, error) {
		if created {
			_ = os.RemoveAll(root)
		} else {
			clear(root)
		}
		return Result{}, err
	}

	files := map[string]string{".gitignore": gitignore}
	switch o.Template {
	case Empty:
		files["stormo.yaml"] = emptyStormoYAML(o)
		files["units/group/unit.yaml"] = fmt.Sprintf("id: group\nname: %s\ndescription: %s\n", q(o.Org+" Group"), q("Shared goals and learnings across "+o.Org+"."))
		files["units/group/knowledge/README.md"] = "# " + o.Org + " group knowledge\n\nPolicy every agent follows, as Markdown files in this folder. It is compiled into each agent's knowledge skill.\n"
		files["agents/README.md"] = "# Agents\n\nOne folder per agent: `agents/<id>/agent.yaml` and `SOUL.md` (docs/instances.md in the engine).\n"
	case Example:
		if err := copyFS(example, root); err != nil {
			return fail(err)
		}
		body, err := os.ReadFile(filepath.Join(root, "stormo.yaml"))
		if err != nil {
			return fail(err)
		}
		files["stormo.yaml"] = renamed(string(body), o)
	}
	for rel, body := range files {
		p := filepath.Join(root, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			return fail(err)
		}
		if err := os.WriteFile(p, []byte(body), 0o644); err != nil {
			return fail(err)
		}
	}
	if _, err := instance.Load(root); err != nil {
		return fail(fmt.Errorf("the new instance does not load: %w", err))
	}
	r := Result{Root: root, Name: o.Name, Org: o.Org, Slug: o.Slug, Template: o.Template}
	if o.Git {
		if _, err := exec.LookPath("git"); err == nil {
			cmd := exec.Command("git", "init", "-q")
			cmd.Dir = root
			if err := cmd.Run(); err != nil {
				return fail(fmt.Errorf("git init: %w", err))
			}
			r.Git = true
		}
	}
	return r, nil
}

// prepare makes root, or accepts it when it exists and is empty; created reports a new directory.
func prepare(root string) (created bool, err error) {
	entries, err := os.ReadDir(root)
	switch {
	case errors.Is(err, fs.ErrNotExist):
		return true, os.MkdirAll(root, 0o755)
	case err != nil:
		return false, err
	}
	for _, e := range entries {
		if e.Name() != ".DS_Store" {
			return false, fmt.Errorf("%s is not empty: a new instance needs an empty or new folder", root)
		}
	}
	return false, nil
}

// clear empties a directory that existed before (it was empty; anything in it is ours).
func clear(root string) {
	entries, _ := os.ReadDir(root)
	for _, e := range entries {
		_ = os.RemoveAll(filepath.Join(root, e.Name()))
	}
}

func copyFS(src fs.FS, root string) error {
	return fs.WalkDir(src, ".", func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if p == "." {
			return nil
		}
		dst := filepath.Join(root, filepath.FromSlash(p))
		if d.IsDir() {
			return os.MkdirAll(dst, 0o755)
		}
		b, err := fs.ReadFile(src, p)
		if err != nil {
			return err
		}
		return os.WriteFile(dst, b, 0o644)
	})
}

// q quotes a value for YAML (a JSON string is a valid YAML double-quoted scalar).
func q(s string) string {
	b, _ := json.Marshal(s)
	return string(b)
}

func emptyStormoYAML(o Options) string {
	return fmt.Sprintf(`# %[1]s: a Stormo instance (the engine's docs/instances.md). Units live in units/, agents in agents/.
name: %[2]s
org: %[3]s
slug: %[4]s
# names: default to %[4]s-stormo, %[4]s/stormo, %[4]s-state, %[4]s-knowledge, %[4]s-shared-docs.
# They name deployed infrastructure and agents' skills: settle them before the first deploy.

# office:            the office's look (docs/core.md in the engine)
#   clocks:
#     - { city: Lisbon, tz: Europe/Lisbon }
`, o.Name, q(o.Name), q(o.Org), o.Slug)
}

var topKey = regexp.MustCompile(`(?m)^(name|org|slug):.*$`)

// renamed gives the example's stormo.yaml the new instance's name, org and slug; comments and the
// rest stay as they are.
func renamed(body string, o Options) string {
	return topKey.ReplaceAllStringFunc(body, func(line string) string {
		switch strings.SplitN(line, ":", 2)[0] {
		case "name":
			return "name: " + q(o.Name)
		case "org":
			return "org: " + q(o.Org)
		default:
			return "slug: " + o.Slug
		}
	})
}
