package slack

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"strings"
)

// node is a JSON value that keeps object key order, so a manifest generated by the engine's own
// tool is re-emitted in its original order.
type node struct {
	kind   byte // 'o' object, 'a' array, 's' scalar
	keys   []string
	vals   []*node
	scalar any // string, json.Number, bool or nil
}

func parseJSON(b []byte) (*node, error) {
	dec := json.NewDecoder(bytes.NewReader(b))
	dec.UseNumber()
	n, err := readNode(dec)
	if err != nil {
		return nil, err
	}
	if _, err := dec.Token(); err != io.EOF {
		return nil, fmt.Errorf("trailing data after JSON value")
	}
	return n, nil
}

func readNode(dec *json.Decoder) (*node, error) {
	t, err := dec.Token()
	if err != nil {
		return nil, err
	}
	switch d := t.(type) {
	case json.Delim:
		switch d {
		case '{':
			n := &node{kind: 'o'}
			for dec.More() {
				kt, err := dec.Token()
				if err != nil {
					return nil, err
				}
				v, err := readNode(dec)
				if err != nil {
					return nil, err
				}
				n.set(kt.(string), v)
			}
			_, err := dec.Token()
			return n, err
		case '[':
			n := &node{kind: 'a'}
			for dec.More() {
				v, err := readNode(dec)
				if err != nil {
					return nil, err
				}
				n.vals = append(n.vals, v)
			}
			_, err := dec.Token()
			return n, err
		}
		return nil, fmt.Errorf("unexpected %v", d)
	default:
		return &node{kind: 's', scalar: t}, nil
	}
}

func (n *node) get(k string) *node {
	if n == nil || n.kind != 'o' {
		return nil
	}
	for i, key := range n.keys {
		if key == k {
			return n.vals[i]
		}
	}
	return nil
}

// set replaces k in place (a key keeps its first position) or appends it.
func (n *node) set(k string, v *node) {
	for i, key := range n.keys {
		if key == k {
			n.vals[i] = v
			return
		}
	}
	n.keys = append(n.keys, k)
	n.vals = append(n.vals, v)
}

func (n *node) del(k string) {
	for i, key := range n.keys {
		if key == k {
			n.keys = append(n.keys[:i], n.keys[i+1:]...)
			n.vals = append(n.vals[:i], n.vals[i+1:]...)
			return
		}
	}
}

func (n *node) str() (string, bool) {
	if n == nil || n.kind != 's' {
		return "", false
	}
	s, ok := n.scalar.(string)
	return s, ok
}

func jsString(s string) string {
	var b bytes.Buffer
	enc := json.NewEncoder(&b)
	enc.SetEscapeHTML(false)
	_ = enc.Encode(s)
	return strings.TrimSuffix(b.String(), "\n")
}

// stringify is two-space indented JSON.
func (n *node) stringify() string {
	var b strings.Builder
	n.write(&b, "")
	return b.String()
}

func (n *node) write(b *strings.Builder, indent string) {
	inner := indent + "  "
	switch n.kind {
	case 'o':
		if len(n.keys) == 0 {
			b.WriteString("{}")
			return
		}
		b.WriteString("{\n")
		for i, k := range n.keys {
			b.WriteString(inner + jsString(k) + ": ")
			n.vals[i].write(b, inner)
			if i < len(n.keys)-1 {
				b.WriteString(",")
			}
			b.WriteString("\n")
		}
		b.WriteString(indent + "}")
	case 'a':
		if len(n.vals) == 0 {
			b.WriteString("[]")
			return
		}
		b.WriteString("[\n")
		for i, v := range n.vals {
			b.WriteString(inner)
			v.write(b, inner)
			if i < len(n.vals)-1 {
				b.WriteString(",")
			}
			b.WriteString("\n")
		}
		b.WriteString(indent + "]")
	default:
		switch v := n.scalar.(type) {
		case nil:
			b.WriteString("null")
		case string:
			b.WriteString(jsString(v))
		case bool:
			fmt.Fprint(b, v)
		case json.Number:
			b.WriteString(v.String())
		}
	}
}
